apiVersion: v1
kind: Service
metadata:
  name: demo-redis
  namespace: demo
  labels:
    app: demo-redis
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: demo-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-redis
  namespace: demo
  labels:
    app: demo-redis
spec:
  selector:
    matchLabels:
      app: demo-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-redis
    spec:
      containers:
        - name: demo-redis
          image: redis:4.0.1-alpine
          ports:
            - containerPort: 6379