# Generated by Django 2.2.4 on 2019-08-13 08:18

from django.db import migrations, models
import djongo.models.fields
import mongo_test_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedModelField(model_container=mongo_test_app.models.Blog, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
