apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-django
  namespace: demo
data:
  MYSQL_ROOT_PASSWORD: pass1234
  MYSQL_DATABASE: demo
  MYSQL_USER: demo
  MYSQL_SERVICE: 127.0.0.1
  DEFAULT-CHARACTER-SET: utf-8
  MYSQL_PASSWORD: pass1234
  MYSQL_PORT: '3306'
  REDIS_HOST: redis